### ISSUE TITLE
Contents and timing of 1.0.7 release

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-parser-combinators#130]
@gourlaysama perhaps #118 (Scala Native) and #119 (Scala.js) are sufficient to justify a 1.0.7 release?

**Comment by etorreborre** [comment]
@gourlaysama can I second one more time this request? This is currently making my builds fail and makes it hard for me to check if everything is fine with the Scala.js version of specs2. Thanks!

**Comment by etorreborre** [comment]
Can we please have a new release @gourlaysama? Thanks.

**Comment by cheeseng** [comment]
@gourlaysama +1 for the new release, thanks!

**Comment by sarahgerweck** [comment]
I have also been bit by the fact that ScalaJS isn't working here. Is there something that makes a release of this library difficult that somebody could help with?

**Comment by lrytz** [comment]
There's an open issue with integrating scala-native into the build / release process: https://github.com/scala/scala-parser-combinators/pull/132#issuecomment-342553814

**Comment by SethTisue** [comment]
@gourlaysama could we have some indication from you, one way or the other, whether this is something you expect to have time for in, say, the next few weeks? if this isn't something you have time for anymore, let us know and we'll see if someone else would like to take over maintainership of the repo.

**Comment by gourlaysama** [comment]
So the current status is this:
 - `1.0.x` currently doesn't publish because of the scala-native support (https://github.com/scala/scala-parser-combinators/pull/132#issuecomment-350270643), which needs some things in sbt-scala-module, which will come with sbt 1 support there (scala/sbt-scala-module#32)
 - I tried doing it without support in the plugin last week wit no success. I have another idea with publishing native manually in `admin/build.sh` that I want to try, but overall this isn't working well. Going that way basically means moving most of the build matrix in bash in `admin.sh`, with the rest in `build.sbt`.

I think we should just revert scala-native support and publish 1.0.7 (with working scala-js this time). Scala-native can wait a little. @SethTisue WDYT?

**Comment by etorreborre** [comment]
@SethTisue @gourlaysama I vote yes :-).

**Comment by SethTisue** [comment]
👍 to reverting Scala Native support for now

**Comment by SethTisue** [comment]
artifacts are on their way to Maven Central right now

**Comment by SethTisue** [comment]
@gourlaysama the only thing I can think of that's left to do here is that https://github.com/scala/scala-parser-combinators/releases/tag/untagged-386d522ae0cc7a9713d8 needn't be marked "draft" anymore

fyi @sjrd

**Comment by gourlaysama** [comment]
Done: https://github.com/scala/scala-parser-combinators/releases/tag/v1.0.7

v1.0.7 is now on Maven Central 🎉 !
