### ISSUE TITLE
Seemingly nondeterministic parser failure

### ISSUE THREAD

**Issue by martinstuder** [scala/scala-parser-combinators#75]
I'm observing weird issues with a parser (`TokenParsers with PackratParsers`) which is based on a left-recursive grammar. The parser fails seemingly randomly. I don't think it's threading issues as I'm instantiating a new parser for each execution of "parse". Also, the parser is stateless except for the parser combinator internals themselves.

Attached is a reproducible example consisting of a lexer, parser and a main which simply calls the "parse" method of the parser. With each run the parser either succeeds or fails to parse the very same input.

[repro.zip](https://github.com/scala/scala-parser-combinators/files/75176/repro.zip)

**Comment by inkytonik** [comment]
I compiled your code with Scala 2.11.7 (just "scalac *.scala") and ran it many times (using "scala com.github.martinstuder.frint.parser.Main"). I have always received the output "ok".

This leads me to believe there is something special about your setup. Can you provide more information? E.g., how are you building the code? Which Scala version are you using? What happens when it fails?

**Comment by toddobryan-amazon** [comment]
That was weird. I wrapped your code in a for-loop and got the exception. Then I put a for-loop in front of your code, and got an exception. I can understand your frustration.

It turns out the problem is builtInOps on line 70 of RLexer. Make it a List instead of a Set. When you map over a Set, you have no idea which order things will come out as, and my guess is that "|" is being added before "||", so "|" gets parsed and the second "|" is the illegal expression it complains about. With List, everything works fine.

If you're worried about efficiency of doing builtInOps.contains(...), then you can create a Set based on the list.

**Comment by martinstuder** [comment]
For the "reproducible" example I'm using sbt in the directory containing the source files (no build.sbt; but the parser combinator library in a lib subfolder). I tried with Scala 2.11.7 and scala-parser-combinators_2.11-1.0.4.jar.

JVM:
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

**Comment by martinstuder** [comment]
Oh, just saw your comment now ...

**Comment by martinstuder** [comment]
Yep, that was it! Thanks so much for the prompt response! Not the first time I'm stumbling over map on Set vs List ... but didn't think anywhere near this in this case ...

**Comment by SethTisue** [comment]
nice catch @toddobryan-amazon
